module.exports = {
  projects: [
    '<rootDir>/packages/nx-plugin-typegraphql',
    '<rootDir>/e2e\\nx-plugin-typegraphql-e2e',
    '<rootDir>/packages/nx-plugin-midway',
    '<rootDir>/e2e\\nx-plugin-midway-e2e',
    '<rootDir>/packages/nx-plugin-prisma',
    '<rootDir>/e2e\\nx-plugin-prisma-e2e',
    '<rootDir>/packages/nx-plugin-serverless',
    '<rootDir>/e2e\\nx-plugin-serverless-e2e',
    '<rootDir>/packages/nx-plugin-esbuild',
    '<rootDir>/e2e\\nx-plugin-esbuild-e2e',
    '<rootDir>/packages/nx-plugin-swc',
    '<rootDir>/e2e\\nx-plugin-swc-e2e',
    '<rootDir>/packages/nx-plugin-vite',
    '<rootDir>/e2e\\nx-plugin-vite-e2e',
    '<rootDir>/packages/nx-plugin-umi',
    '<rootDir>/e2e\\nx-plugin-umi-e2e',
    '<rootDir>/packages/nx-plugin-ice',
    '<rootDir>/e2e\\nx-plugin-ice-e2e',
    '<rootDir>/packages/esbuild-plugin-decorator',
    '<rootDir>/packages/esbuild-plugin-node-externals',
  ],
};
